# Generated by Django 4.1.6 on 2023-02-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="product_name")),
                ("code", models.CharField(max_length=255, verbose_name="product_code")),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("unit", models.CharField(blank=True, max_length=255, null=True)),
                ("image_url", models.ImageField(upload_to="img_product")),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Product_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="img_product")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="shop.item",
                    ),
                ),
            ],
        ),
    ]
