# Generated by Django 4.1.6 on 2023-02-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="item",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
