# Generated by Django 4.1.6 on 2023-02-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_orderitem_item_remove_orderitem_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Customer Email"),
                ),
                ("amount", models.IntegerField(verbose_name="amount")),
                ("stripe_payment_intent", models.CharField(max_length=200)),
                (
                    "has_paid",
                    models.BooleanField(default=False, verbose_name="payment status"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.item",
                        verbose_name="Item",
                    ),
                ),
            ],
        ),
    ]
