# Generated by Django 4.1.6 on 2023-02-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orderdetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderDetail",
        ),
    ]
