# Generated by Django 4.1.6 on 2023-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_orderitem_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("1_cart", "cart"),
                    ("2_waiting_for_payment", "waiting_for_payment"),
                    ("3_paid", "paid"),
                ],
                default="1_cart",
                max_length=32,
            ),
        ),
    ]
